title: Teleroute API documentation
description: Teleroute API documentation
url: 'https://api-docs.teleroute.com/'
google_analytics_key: UA-110315829-1
permalink: pretty
baseurl: null
timezone: Etc/UTC
collections:
  documentation:
    title: Documentation
    position_number: 1
  auth_api:
    title: Authentication
    position_number: 2
  freight_posting_api:
    title: Freight posting
    position_number: 3
  freight_searching_api:
    title: Freight searching
    position_number: 4
  vehicle_posting_api:
    title: Vehicle posting
    position_number: 5
  reference_data:
    title: Reference data
    position_number: 99
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - readme.md
  - LICENSE
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      type: documentation
    values:
      _hide_content: true
  - scope:
      type: auth_api
    values:
      _hide_content: true
  - scope:
      type: freight_posting_api
    values:
      _hide_content: true
  - scope:
      type: freight_searching_api
    values:
      _hide_content: true
  - scope:
      type: vehicle_posting_api
    values:
      _hide_content: true
types:
  - get
  - put
  - delete
  - post
languages:
  bash: Bash
  javascript: JavaScript
  json: JSON
_options:
  content_markdown:
    format: p h2 h3 h4
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    code: true
    image: true
    table: true
    styles: /css/editor.css
