title: Teleroute API documentation
description: Teleroute API documentation.
url: 'https://teleroute.com'
google_analytics_key: null
permalink: pretty
baseurl: null
timezone: Etc/UTC
collections:
  documentation:
    title: Documentation
    position_number: 1
  auth_api:
    title: Authentication API
    position_number: 2
  freight_posting_api:
    title: Freight posting API
    position_number: 3
#  freight_searching_api:
#    title: Freight searching API
#    position_number: 4
#  vehicle_posting_api:
##    title: Vehicle posting API
#    position_number: 5
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - readme.md
  - LICENSE
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      type: documentation
    values:
      _hide_content: true
  - scope:
      type: auth_api
    values:
      _hide_content: true
  - scope:
      type: freight_posting_api
    values:
      _hide_content: true
  - scope:
      type: freight_searching_api
    values:
      _hide_content: true
  - scope:
      type: vehicle_posting_api
    values:
      _hide_content: true
types:
  - get
  - put
  - delete
  - post
languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby
_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
